include(${CMAKE_CURRENT_LIST_DIR}/DownloadPackage.cmake)
DownloadPackage(SDL2 http://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip SDL2_SOURCE_DIR)

if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    set(ARCH x64)
else()
    set(ARCH x86)
endif()

if(CYGWIN)
    set(CMAKE_IMPORT_LIBRARY_SUFFIX .dll)
ENDIF()

add_library(SDL2::CORE UNKNOWN IMPORTED)
set_target_properties(SDL2::CORE PROPERTIES
#    IMPORTED_LOCATION ${SDL2_SOURCE_DIR}/lib/${ARCH}/SDL2main.lib
    IMPORTED_LOCATION ${SDL2_SOURCE_DIR}/lib/${ARCH}/SDL2${CMAKE_IMPORT_LIBRARY_SUFFIX}
    INTERFACE_INCLUDE_DIRECTORIES ${SDL2_SOURCE_DIR}/include
    INTERFACE_COMPILE_DEFINITIONS SDL_MAIN_HANDLED
)

set(DLL ${SDL2_SOURCE_DIR}/lib/${ARCH}/SDL2.dll)
FILE(COPY ${DLL} DESTINATION ${CMAKE_BINARY_DIR})
